#######################################################################
#
# XXX Include Functions
#
# Temporary workarounds for known upstream bugs and distribution issues.
# Each function tracks an upstream issue and should be reverted once
# fixed upstream or in base.
#
# "Nothing is more permanent than a temporary solution"
#
#######################################################################

#######################################################################
# Distribution Set variables and functions
#

# These should be fixed in base.txz
_xxx_remove_extra_dist_files() {
	# Remove debug files present in base.txz
	if ! nano_distributions_contains "-dbg.txz "; then
		tgt_rm usr/lib/debug
	fi
	# Remove lib32 files present in base.txz
	if ! nano_distributions_contains " lib32"; then
		tgt_rm libexec/ld-elf32.so.1
		tgt_rm usr/bin/ldd32
		tgt_rm usr/libexec/ld-elf32.so.1
	fi
	# Remove test files present in base.txz
	if ! nano_distributions_contains " tests.txz "; then
		tgt_rm usr/tests
		tgt_rm usr/lib/libxo/encoder/test.enc
		tgt_rm usr/share/man/man7/tests.7.gz
	fi
}

# Already fixed upstream
# https://github.com/libarchive/libarchive/pull/3008
# Account for a bug in libarchive, where the first entry is "/."
_xxx_libarchive_mtree_bug() {
	sed -i "" -e 's|^/\. |\. |' "$NANO_METALOG"
}

#######################################################################
# freebsd-base(7) (pkgbase) variables and functions
#

# Append metalog entries for directories that lack pkg tags in
# the given mtree spec.  This should be fixed in pkg:
# https://github.com/freebsd/pkg/issues/2672
# $1 = mtree filename (under NANO_SRC/etc/mtree)
# $2 = base dir prefix to prepend
_xxx_get_untagged_directories_from_mtree() {
	local mtree="$1"
	local base_dir="$2"

	cat "${NANO_SRC}/etc/mtree/${mtree}" |
	    mtree -C -K uname,gname,tags | grep -v tags |
	    sed -e "s|^\.|\.${base_dir}|g" >> "$NANO_METALOG"
}

# mtree: ./boot/dtb/arm: missing directory in specification
#       These directories are missing from BSD.root.dist, however
#       I do not want to add them to the mtree.  These must exist
#       only for arm/arm64
_xxx_add_missing_boot_dtb() {
	tgt_dir boot/dtb/arm
	tgt_dir boot/dtb/freescale
	tgt_dir boot/dtb/marvell
	tgt_dir boot/dtb/nvidia
	tgt_dir boot/dtb/qcom
}

#
# Add an entry to the metalog
# $1=file/direcrory, $2=mode (optional), $3=metalog file (optional)
#
metalog_add_data() {
	local entry metalog mode type

	entry="$1"
	if [ -f "${NANO_WORLDDIR}/${entry}" ]; then
		type="file"
		mode=${2:-0644}
	elif [ -d "${NANO_WORLDDIR}/${entry}" ]; then
		type="dir"
		mode=${2:-0755}
	else
		err "metalog_add_data: ${entry} not found"
	fi
	metalog=${3:-$NANO_METALOG}
	if [ -n "$metalog" ]; then
		printf "%s type=%s uname=%s gname=%s mode=%s\n" \
		    "$entry" "$type" "$NANO_DEF_UNAME" "$NANO_DEF_GNAME" "$mode" >> "$metalog"
	fi
}
